name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Deploy
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          # Remove everything except .git and dist
          git rm -rf .
          git checkout .gitignore
          
          # Move dist contents to root
          mv dist/* .
          mv dist/.* . 2>/dev/null || true
          rmdir dist
          
          # Add and commit everything
          git add .
          git commit -m "Deploy built files to root"
          
          # Push changes
          git push origin main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 